// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH8qzRMAqtkOPoBW4EPthGYs_RT-cp7jQ',
    appId: '1:241120934305:web:e8c903d9a14f86886333e0',
    messagingSenderId: '241120934305',
    projectId: 'spotify-4150e',
    authDomain: 'spotify-4150e.firebaseapp.com',
    storageBucket: 'spotify-4150e.appspot.com',
    measurementId: 'G-HBP4E1GXTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZlAgUdFPHgcSmyigb9GZtlbadGToNBoA',
    appId: '1:241120934305:android:9482aa5a49b9c3d76333e0',
    messagingSenderId: '241120934305',
    projectId: 'spotify-4150e',
    storageBucket: 'spotify-4150e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChfyYxGUW56YOO4CBy1CkjI4bM-bFuUv4',
    appId: '1:241120934305:ios:ade5bed36c9cb2d16333e0',
    messagingSenderId: '241120934305',
    projectId: 'spotify-4150e',
    storageBucket: 'spotify-4150e.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChfyYxGUW56YOO4CBy1CkjI4bM-bFuUv4',
    appId: '1:241120934305:ios:ade5bed36c9cb2d16333e0',
    messagingSenderId: '241120934305',
    projectId: 'spotify-4150e',
    storageBucket: 'spotify-4150e.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH8qzRMAqtkOPoBW4EPthGYs_RT-cp7jQ',
    appId: '1:241120934305:web:74c6d759a292ec266333e0',
    messagingSenderId: '241120934305',
    projectId: 'spotify-4150e',
    authDomain: 'spotify-4150e.firebaseapp.com',
    storageBucket: 'spotify-4150e.appspot.com',
    measurementId: 'G-VYXYZT6MG5',
  );
}
